- hosts: all
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled
    register: selinux

  - name: Update kernel
    yum:
      name: kernel
      state: latest
    register: kernel

  - name: Reboot machine
    reboot:
      reboot_timeout: 300
    when: selinux.changed or kernel.changed
